# Generated by Django 3.2.3 on 2021-06-11 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Car', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='save_cars',
            field=models.ManyToManyField(related_name='save_cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to=settings.AUTH_USER_MODEL),
        ),
    ]
