# Generated by Django 3.2.3 on 2021-07-08 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesCarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Car.carsmodel')),
            ],
            options={
                'db_table': 'images_car',
            },
        ),
    ]
