# Generated by Django 3.2.3 on 2021-07-12 11:20

import apps.Car.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_imagescarmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagescarmodel',
            name='img',
            field=models.ImageField(upload_to=apps.Car.services.images_car_upload),
        ),
    ]
