# Generated by Django 3.2 on 2021-04-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersprofilemodel',
            table='users_profile',
        ),
    ]
